name: Redis

on:
  push:
    branches: [ "develop" ]
  pull_request:
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: export TF_VAR_AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: export TF_VAR_AWS_SECRET_KEY_ID=${{ secrets.AWS_SECRET_KEY_ID }}
      - run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
